#!/bin/bash

#create N permutation of MAP, a popmap with sex labels. Used for global and per chromosomes permutation.

#variable
DAT=$1
MAP=$2
N=$3
Output="96_permutations"

#modules
module load vcftools/0.1.16


#script:
for (( i=1; i<=$N; i++ ))
do
    grep R1 ${MAP}/R_$i | cut -f1 >$MAP/R1
    grep R2 $MAP/R_$i | cut -f1 >$MAP/R2
    vcftools --gzvcf $DAT --freq2 --keep ${MAP}/R1 --out ${Output}/R1
    vcftools --gzvcf $DAT --freq2 --keep ${MAP}/R2 --out ${Output}/R2
    if [  $i -eq 1 ]
     then
         cut -f1,2 ${Output}/R1.frq >${Output}/tmp_pos
    fi
     cut -f5 ${Output}/R1.frq > ${Output}/tmp_freqR1
    cut -f5 ${Output}/R2.frq > ${Output}/tmp_freqR2
     cut -f4 ${Output}/R1.frq > ${Output}/tmp_NR1
         cut -f4 ${Output}/R2.frq > ${Output}/tmp_NR2

     paste ${Output}/tmp_pos ${Output}/tmp_NR1 ${Output}/tmp_freqR1 ${Output}/tmp_NR2 ${Output}/tmp_freqR2 >$Output/maf_freq_$i
     sed -i "1 s/.*/scaf\tpos\tn_males_allele_covered\tmale_freq\tn_females_allele_covered\tfemale_freq/" $Output/maf_freq_$i
    rm $MAP/R1 $MAP/R2
done
